version: '3'

services:
  kojiweb:
    build: kojiweb
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./kojiweb/config/httpd:/etc/httpd:z"
      - "./kojiweb/config/koji-gc:/etc/koji-gc:z"
      - "./kojiweb/config/koji-hub:/etc/koji-hub:z"
      - "./kojiweb/config/koji-shadow:/etc/koji-shadow:z"
      - "./kojiweb/config/koji.conf.d:/etc/koji.conf.d:z"
      - "./kojiweb/config/kojira:/etc/kojira:z"
      - "./kojiweb/config/kojiweb:/etc/kojiweb:z"
      - "./kojiweb/config/koji.conf:/etc/koji.conf:z"
      - "./ssl:/etc/pki/koji:z"
      - "/mnt/koji:/mnt/koji:z"

  kojidb:
    image: docker.io/library/postgres:9.6
    volumes:
      - "./kojidb/data:/var/lib/postgresql/data:z"
      - "./kojidb/init.sql:/docker-entrypoint-initdb.d/init.sql:z"
    environment:
      - POSTGRES_USER=koji
      - POSTGRES_PASSWORD=koji
      - POSTGRES_DB=koji